server:
  port: 80

spring:
  application:
    name: apple-cloud-gateway-zuul

###定义zuul反向代理规则
zuul:
  routes:
    consumer-user: /user-zuul/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

#logging:
  #level:
 #   com.netflix: debug


